### ISSUE TITLE
Esportazione RNDT compliant - GUI impostazione XSL in CSW virtuale

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#21]
Possibilità di impostare un XSL di trasformazione a livello di endpoint di CSW virtuale.

**Comment by taba90** [comment]
working on this

**Comment by etj** [comment]
Given a virtual CSW, we want to apply an XSL stylesheet *before* the `summary`/`brief`/`full` transformation.

The XSL stylesheet will be created inside a directory `plugin/SCHEMA/present/csw/virtual`, e..g:
   https://github.com/geonetwork/core-geonetwork/tree/master/schemas/iso19139/src/main/plugin/iso19139/present/csw

- The XSL can be useful where a schema has some internal mechanism or information that should not be made public through the given virtual entrypoint.
- The XSL has to be applied before the summary/brief/full transformation, bc it also transforms the output schema.

One problem is that, when a getRecords is resolved, each record found is modified according the `/present/csw` files in its own schema directory; this means we can't select a single xsl file from a single schema directory, bc we don't know which records a query will return.
So, we could have a Virtual CSW to only return metadata belonging to a single schema; if such filter exists in a VCSW, an XSL within its `present/csw/virtual` can be choosen in order to modifiy the output metadata.

To do:
- [x] In the virtual CSW GUI, add a dropdown to optionally filter a single schema within the ones allowed in the GeoNetowrk instance
- [x] In the virtual CSW GUI, add a dropdown to optionally choose an XSL file, from those in the optional directory `plugin/SCHEMA/present/csw/virtual`
- [x] When a getRecords/getRecordById operation is executed in a virtual CSW, apply the optional schema filtering
- [x] When a getRecords/getRecordById operation is executed in a virtual CSW, apply the optional XSL transformation

**Comment by taba90** [comment]
Here the pull request https://github.com/geosolutions-it/core-geonetwork/pull/26

**Comment by tdipisa** [comment]
The RNDT metadata are in the right format directly inside the GN DB, therefore a XSL trasformation is not needed now.
